/* eslint-disable react-refresh/only-export-components */
export const PROJECTS = [
    {
        id: 1,
        name: 'Kitchens Catalog',
        image: '/projects/kitchens-catalog.jpg',
        shorts: 'A Portfolio for an aluminum workshop with 3D Catalog for kitchens with a good UI',
        description: 'the site aims to show the brand visual identity and the 3D models of the kitchens',
        link: 'https://gosmart-3d-catalog.vercel.app/',
        usedLibs: [],
        functions: [],
        responsive: true,
    },
    {
        id: 2,
        name: '3D Building Booklet',
        image: '/projects/3d-building-booklet.jpg',
        shorts: 'A 3D Building Booklet with a good UI',
        description: 'A fully responsive website showing the building features, location and services with ready to download the building booklet in pdf format and 3d models',
        usedLibs: ['Vitejs-react', 'aos', 'tailwind', 'daisyui', 'react-icons', 'react-router-dom'],
        functions: ['sections animations', 'sending emails', 'responsive', ''],
        link: 'https://aly-moaaz.vercel.app/',
        responsive: true,
        screenshots: [],
    },
    {
        id: 3,
        name: 'Sketto Cafe',
        image: '/projects/sketto-cafe.jpg',
        shorts: 'An Elegant cafe website with a good UI and a showing the brand visual identity',
        description: ', A fully responsive website in 4 pages representing the brand idientity ',
        usedLibs: ['javescript', 'html', 'css', 'bootstrap'],
        functions: ['responsive design', 'scroll up', 'display mode'],
        link: 'https://classic-coffee.vercel.app/',
        responsive: false,
    },
    {
        id: 4,
        name: 'Go Smart Soultions',
        image: '/projects/go-smart.jpg',
        shorts: 'Portfolio for a Software Services and Degital Transformation Company ',
        description: '',
        usedLibs: ['Vitejs-react', 'react-router-hash-link'],
        functions: ['display mode', 'infinit sliders'],
        link: '#',
        responsive: true,
    },
    {
        id: 5,
        name: 'Logistics',
        image: '/projects/logis.jpg',
        shorts: 'A protfolio A Logistics company shows location and services with conatct form.',
        description: '',
        usedLibs: ['reactjs', 'firebase', 'firestore', 'firebase storage', 'prop-types', 'react-query', 'react-hook-form'],
        functions: ['google Signin', 'creating admin dashboard', 'reading files', 'upload images', 'validating forms', 'save user data', 'paginate', 'firebase hosting', 'authorization'],
        link: '#',
        responsive: true,
    },
    {
        id: 6,
        name: 'Landing Page',
        image: '/projects/landing-page.jpg',
        shorts: 'A landing page for a course registration connected to firebase',
        description: '',
        usedLibs: [],
        functions: ['responsive design', 'dynamic nav bar', 'manipulating DOM'],
        link: 'https://go-smart-solutions.vercel.app/',
        responsive: true,
    },
    {
        id: 7,
        name: 'Custom Ticket System',
        image: '/projects/custom-app-customer-support.jpg',
        shorts: 'A custom ticket system for customer technical support department for an egyptian port ',
        description: '',
        usedLibs: [],
        functions: ['ticket system'],
        link: 'https://github.com/blacksnowsoon/adabia_port',
        responsive: true,
    },
    {
        id: 8,
        name: 'Custom Task Manager',
        image: '/projects/it-tasks.jpg',
        shorts: 'A cutom task manager for the IT department team of an adabia port ',
        description: 'The app aims to help the IT department team to manage their tasks and projects, enhanced reports for the team increase productivity and showing user activity',
        link: 'https://github.com/blacksnowsoon/adabia_port',
        usedLibs: [],
        functions: ['ticket system'],
        responsive: true,
    },
    {
        id: 9,
        name: 'Custom Project Management System',
        image: '/projects/custom-project-manager.jpg',
        shorts: 'A cutom project manager for the PMIS team of an egyptian port',
        description: 'the app aims to help the application team to manage their projects and tasks, enhanced reports for the team increase productivity and showing user activity',
        link: 'https://github.com/blacksnowsoon/adabia_port',
        usedLibs: [],
        functions: [],
        responsive: true,
    },
    

]
export const COMMING_SOON = [
    {
        id: "10",
        name: 'POS Retail System',
        image: 'pos-375x475.png',
        shorts: 'Desktop web based Application POS system with full inventory management',
        description: 'A desktop web based application work locally for retail stores with full inventory management and order management, Users Privileges and more',
        link: '/#contact',
        hasLink: false,
        usedLibs: ['HTML', 'CSS', 'jQuery', 'Bootstrap', 'electron', 'nodejs', 'DataTable',],
        functions: ['NoSQL', 'users & Permissions', 'bills history', 'sorting', 'Export data CSV', 'Export data PDF', 'stock alarm', 'Standalone app'],
        responsive: false,
    }
]


export const CERTIFICATS = [
    {
        id: 1,
        name: 'ERP Systems',
        pdf: '/certificates/ERP.png',
    },
    {
        id: 2,
        name: 'JavaScript',
        pdf: '/certificates/javascript.png',
    },
    {
        id: 3,
        name: 'SQL',
        pdf: '/certificates/sql.png',
    },
    {
        id: 4,
        name: 'React',
        pdf: '/certificates/react-2.png',
    },
    {
        id: 5,
        name: 'Frontend',
        pdf: '/certificates/frontEnd.png',
    },
    {
        id: 6,
        name: 'HTML - CSS',
        pdf: '/certificates/HTML.png',
    },
    {
        id: 7,
        name: 'React',
        pdf: '/certificates/react-1.png',
    }
]
